kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-expense
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-050e2bfa4a8a07d3a
  directoryPerms: "700"
  basePath: "/expense"